apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-devex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-devex
  template:
    metadata:
      labels:
        app: local-devex
    spec:
      containers:
        - name: local-devex
          image: local/devex:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: local-devex-svc
spec:
  type: NodePort
  selector:
    app: local-devex
  ports:
    - port: 8080
      targetPort: 8080
